apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
  name: hello-world
  
spec:
  selector: 
    app: hello-world
  type: NodePort  # use LoadBalancer as type here
  ports:
    - port: 8084
      targetPort: 8084
